//! COCO 80-class labels used by YOLO11n.

pub const COCO_NAMES: [&str; 80] = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
];

/// Distinct UI/box colors (RGB) cycled by class id.
pub fn color_for(class_id: usize) -> (u8, u8, u8) {
    const PALETTE: [(u8, u8, u8); 15] = [
        (255, 99, 71),
        (50, 205, 50),
        (30, 144, 255),
        (255, 215, 0),
        (186, 85, 211),
        (0, 206, 209),
        (255, 140, 0),
        (127, 255, 212),
        (255, 105, 180),
        (173, 255, 47),
        (64, 224, 208),
        (255, 69, 0),
        (147, 112, 219),
        (0, 191, 255),
        (240, 230, 140),
    ];
    PALETTE[class_id % PALETTE.len()]
}

pub fn hex_color(class_id: usize) -> String {
    let (r, g, b) = color_for(class_id);
    format!("#{r:02x}{g:02x}{b:02x}")
}
